### ISSUE TITLE
Receiving error "attempt to index field 'ctx' (a nil value)"

### ISSUE THREAD

**Issue by miversen33** [stevearc/dressing.nvim#128] opened 2023-11-11 21:04 UTC
**Describe the bug**
I am receiving an error when I attempt to execute `vim.lsp.buf.code_action`. At first I thought this was something broken in my configuration (which is probably still correct) but it seems that dressing assumes `items` (in [dressing.select.telescope.custom_kind.codeaction](https://github.com/stevearc/dressing.nvim/blob/master/lua/dressing/select/telescope.lua#L8) will always have a context associated with them. Might be true, might not. I am unsure

A picture is worth a thousand words so here is a screenshot of the error
![image](https://github.com/stevearc/dressing.nvim/assets/2640668/5aed98dc-0f6c-4a15-a7d7-ef96b878d062)

**System information**

- OS: linux
- Neovim version: 0.10.0-dev-ebe489d
- Is this related to a specific `vim.ui.select` backend? If so, which one? Telescope
- Dressing config: 

```lua
-- Paste your call to require("dressing").setup(...) in here
require("dressing").setup()
```

**To Reproduce**

1. Open a file that has a running LSP (that provides code actions). In my case I am using `rust-analyzer` but I have tested this with a few different LSPs
2. Move cursor to a position that should have a code action available
3. Execute `:lua vim.lsp.buf.code_action`

If possible, provide a minimal file that will trigger the issue (see
[tests/manual](https://github.com/stevearc/dressing.nvim/tree/master/tests/manual)
for examples of short ways to call `vim.ui.*`):

Given that you need a handful of things setup for this, I do not know that I can provide a simple configuration file to reliably trigger the issue (though you can always pull my [dotfiles](https://github.com/miversen33/miversen-dotfiles/tree/master/editors/nvim) down and use them

**Screenshots**

**Additional context**
This issue is localized to only "older" versions of the nightly release. I have tested on the following Neovim version
- neovim-0.10.0-dev-e9b: ✅
- neovim-0.10.0-dev-422: ❌
- neovim-0.10.0-dev-585: ❌
- neovim-0.10.0-dev-ebe: ❌
- neovim-0.9.4-stable:  ✅

Might I suggest updating the following code snippet
```lua
-- https://github.com/stevearc/dressing.nvim/blob/master/lua/dressing/select/telescope.lua#L28C1-L32C10
      if vim.fn.has("nvim-0.10") == 1 then
        client_id = item.ctx.client_id
      else
        client_id = item[1]
      end
```

to something like?

```lua
    client_id = item.ctx and item.ctx.client_id or item[1]
```

**Comment by ariel-frischer** [comment] 2023-11-11 22:29
Same

**Comment by jamestrew** [comment] 2023-11-11 23:55
I had the same issue but updating neovim fixes this it seems.
I'm on `NVIM v0.10.0-dev-1532+gc23dd7c9e` but it looks like it's been fixed for a few days https://github.com/stevearc/dressing.nvim/issues/126#issuecomment-1799470315

**Comment by stevearc** [comment] 2023-12-01 07:26
This was caused by a backwards-incompatible change in nvim nightly. It was fixed in the linked issue, but that means that if you had an _older_ version of nightly it would now error. If you update to the newest nightly and newest dressing it should be error-free

**Closed by stevearc** 2023-12-01 07:26 UTC
Labels: bug
